/*
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.1 (the "License");  you may not use this file except in 
 * compliance with the License.  You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
 * the specific language governing rights and limitations under the License.
 *
 * The Original Code is Protege-2000.
 *
 * The Initial Developer of the Original Code is Stanford University. Portions
 * created by Stanford University are Copyright (C) 2007.  All Rights Reserved.
 *
 * Protege was developed by Stanford Medical Informatics
 * (http://www.smi.stanford.edu) at the Stanford University School of Medicine
 * with support from the National Library of Medicine, the National Science
 * Foundation, and the Defense Advanced Research Projects Agency.  Current
 * information about Protege can be obtained at http://protege.stanford.edu.
 *
 */

/* Generated By:JavaCC: Do not edit this line. ManchesterOWLParserConstants.java */
package edu.stanford.smi.protegex.owl.model.classparser.manchester;

public interface ManchesterOWLParserConstants {

  int EOF = 0;
  int SOME = 6;
  int ALL = 7;
  int HAS = 8;
  int MIN = 9;
  int MAX = 10;
  int EXACT = 11;
  int AND = 12;
  int OR = 13;
  int NOT = 14;
  int OPENPAR = 15;
  int CLOSEPAR = 16;
  int OPENSQPAR = 17;
  int CLOSESQPAR = 18;
  int UNBOUNDEDVAL = 19;
  int CLASS_EXPR_COMMENT = 20;
  int INTEGER_LITERAL = 21;
  int FLOATING_POINT_LITERAL = 22;
  int EXPONENT = 23;
  int STRING_LITERAL = 24;
  int ONE_OF = 25;
  int IDENTIFIER = 26;
  int DATATYPEID = 27;
  int LETTER = 28;
  int DIGIT = 29;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SOME>",
    "<ALL>",
    "<HAS>",
    "<MIN>",
    "<MAX>",
    "<EXACT>",
    "<AND>",
    "<OR>",
    "<NOT>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"..\"",
    "\"//\"",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "\"owl:oneOf{\"",
    "<IDENTIFIER>",
    "<DATATYPEID>",
    "<LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\",\"",
  };

}
